services:
  - type: web
    name: coffee-wp
    runtime: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/wordpress-on-render
    branch: main
    envVars:
      - key: WORDPRESS_DB_HOST
        sync: false
      - key: WORDPRESS_DB_NAME
        sync: false
      - key: WORDPRESS_DB_USER
        sync: false
      - key: WORDPRESS_DB_PASSWORD
        sync: false
    healthCheckPath: /
